set(headers ${headers}
	src/FUCK-Host.h
	src/FUCK-Man.h
	src/FUCK-Settings.h
	src/FUCK-Styles.h
	src/FUCK_API.h
	src/ImGui/Audio.h
	src/ImGui/Backend/imgui_default.h
	src/ImGui/Backend/imgui_impl_skyrim.h
	src/ImGui/FormComboBox.h
	src/ImGui/Graphics.h
	src/ImGui/IconsFontAwesome6.h
	src/ImGui/IconsFonts.h
	src/ImGui/Overlays.h
	src/ImGui/Renderer.h
	src/ImGui/Styles.h
	src/ImGui/Util.h
	src/ImGui/Widgets.h
	src/PCH.h
	src/System/Compat.h
	src/System/Console.h
	src/System/Hooks.h
	src/System/Hotkeys.h
	src/System/Input.h
	src/System/InputMap.h
	src/System/Journal.h
	src/System/Papyrus.h
	src/System/Settings.h
	src/System/Translation.h
	src/System/Utils.h
)
