set(sources ${sources}
	src/FUCKHost.cpp
	src/FUCKMan.cpp
	src/ImGui/Backend/imgui_impl_win32.cpp
	src/ImGui/Graphics.cpp
	src/ImGui/IconsFonts.cpp
	src/ImGui/Overlays.cpp
	src/ImGui/Renderer.cpp
	src/ImGui/Styles.cpp
	src/ImGui/Util.cpp
	src/ImGui/Widgets.cpp
	src/PCH.cpp
	src/System/Compat.cpp
	src/System/Console.cpp
	src/System/Hooks.cpp
	src/System/Hotkeys.cpp
	src/System/Input.cpp
	src/System/Papyrus.cpp
	src/System/Settings.cpp
	src/System/Translation.cpp
	src/main.cpp
)
